scottrippey/next-router-mock

src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/router.test.tsx

- add `locale` and `locales` to MemoryRouter
- update `push` signature to match next/router and allow options
resolve #2

feat: add locale support

---

src/MemoryRouter.test.tsx
src/MemoryRouter.tsx

Since the `memoryRouter.locales` is not typed nor has a default value. 
The type inferred is `never` instead of `string[]`
Added a small test case to make show the typing error.
@scottrippey do you want an issue with the PR?

fix(i18n): add typing to locales to fix the never type by default

---

README.md
package-lock.json
package.json
src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/next-link.test.tsx
src/router.tsx

Adds documentation for using `next-router-mock` with `next/link`
TODO:

Add documentation for using `next/link`

---

package-lock.json
package.json
src/MemoryRouter.tsx

When rendering 10+ links, the native `events` module spits out a `MaxListeners` warning.
This PR switches to using `mitt`, which is the same library that Next uses, and does not have the `MaxListeners` warnings.

Use Mitt events to avoid warnings

---

README.md
package-lock.json
package.json
src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/lib/mitt/index.ts
src/next-link.test.tsx
src/router.test.tsx
src/router.tsx

- Add support for `routeChangeStart`
- Make `push` async and emit `routeChangeComplete` async
- Use [Next.js `mitt` implementation](https://github.com/vercel/next.js/blob/5544adc481f8821567e947a6e6d51d9d68ebd367/packages/next/shared/lib/mitt.ts#L25) which supports passing an array of event objects
- Pass `url` and `{ shallow }` event arguments
Thanks for this library, it TOTALLY simplified all my router-based mocking and tests. I just needed the other event and to ensure the right URLs are being passed around.

feat(MemoryRouter): Add routeChangeStart and pass router event arguments

---

package-lock.json
package.json
src/MemoryRouter.tsx

My bad, I didn't realize `setImmediate` is a Node-only feature!  
This fix allows the lib to be used in a real browser.

fix: Use setTimeout instead of setImmediate

---

MemoryRouterProvider/index.js
MemoryRouterProvider/next-10.js
MemoryRouterProvider/next-10/package.json
MemoryRouterProvider/next-11.js
MemoryRouterProvider/package.json
README.md
async/index.js
async/package.json
package-lock.json
package.json

Removes auto-detect, which doesn't work with Storybook (because Webpack automatically imports both versions).
Also, use `package.json` top-level import paths, so that types are kept intact.

feature(next-v11): removed auto-detect

---

src/useMemoryRouter.tsx

Fixes #25 
Unfortunately, I couldn't create a test case to reproduce, but the problem is a common one so it'll have to remain untested.

fix: ensure we don't call `setRouter` after component is unmounted

---

src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/dynamic-routes/extensions-10.ts
src/dynamic-routes/extensions-11.1.ts
src/dynamic-routes/path-parser.ts

In writing tests for our project, a coworker and I stumbled across a bit of functionality that wasn't quite right with the new dynamic routes feature. Query strings were being dropped in the `asPath` property of the router.
It turns out that the best way to solve this was to add catch-all route handling to the `getRouteAsPath` function and use that across the board. Doing so means that we no longer need the additional composite type `UrlObjectWithPath`, so that was removed as well.

Add query string to asPath in dynamic routing

---

README.md
src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/index.test.tsx
src/useMemoryRouter.test.tsx
src/useMemoryRouter.tsx

this PR adds support for two router events (see [https://nextjs.org/docs/api-reference/next/router#routerevents](https://nextjs.org/docs/api-reference/next/router#routerevents)):
- hashChangeStart
- hashChangeComplete
it uses the current url of the MemoryRouter to detect if the `hash` or the `route` was changed and triggers only the matching events (that's the behaviour of next 11)
unfortunately the unit will now test fail if the previous test navigated to the same route.  
I adjusted the test (second commit) to go to a dedicated route instead but I am not sure if this is the desired solution

feature(events): add hashChangeStart and hashChangeComplete

---

src/MemoryRouterProvider/MemoryRouterProvider-10.tsx
src/MemoryRouterProvider/MemoryRouterProvider-11.1.tsx

Explicitly define `children` for React 18 compat

---

MemoryRouterProvider/next-11/package.json
MemoryRouterProvider/next-12/package.json
README.md
dynamic-routes/next-11/package.json
dynamic-routes/next-12/package.json
package-lock.json
package.json
src/dynamic-routes/extensions-12.ts

Adds compatibility for `dynamic-routes` with Next v12.
Also adds explicit path names for `next-11`, for forward compatibility.
Fixes #44

Next 12 compatibility

---

README.md
src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/dynamic-routes/createDynamicRouteParser.test.tsx

Fixes #63 
Added `as` as new optional param within `setCurrentUrl` to enable setting up an asPath.
Depending on if `as` is defined, `_setCurrentUrl` differentiates how `asPath` is defined:
* if `as` is defined, the already existing url parsing logic is reused in order to compute a correct `asPath`.
* if `as` is undefined, the previous default logic is applied.

added support for as param in setCurrentUrl

---

src/MemoryRouter.tsx

Fixed #70 
In _setCurrentUrl, Modified the `if` statement to run even when as is `undefined` and `null`

add null check in _setCurrentUrl

---

README.md
src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/dynamic-routes/createDynamicRouteParser.test.tsx
src/index.test.tsx
src/next-link.test.tsx
src/useMemoryRouter.test.tsx

This adds support for `route`
Since `route` and `pathname` are always exactly the same we can use the same values for both.

Add route support

---

src/MemoryRouter.tsx
src/urls.ts
tsconfig.json

- Removes the dependency on Node's built-in `url` and `querystring` modules
- This allows the package to work in Storybook without needing polyfills
- Addresses #72

Eliminate dependency on Node's `url` and `querystring` and use `URL` and `URLSearchParams`

---

src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/index.test.tsx

Ensures that when pushing an empty path, like `router.push("")` or `router.push({ pathname: "", query: { foo: 'bar' } })`, the parsed path will contain at least a `"/"`

Fix: normalize empty paths to ensure they always have at least a `/`

---

src/useMemoryRouter.test.tsx
src/useMemoryRouter.tsx

Ensures a hash-only change will trigger a component rerender
Addresses #84

Fix: ensure a hash-only change gets rerendered

---

src/MemoryRouter.test.tsx
src/next-link.test.tsx
src/urls.ts

starting with 0.9.4, multi-valued query parameters don't seem to work anymore - is that on purpose? am I doing something wrong?
added a failing test for reproduction.

repro: failing test for multi-valued parameters

---

README.md

Use `jest.requireActual` to avoid using a CommonJS `require` statement .
In my TS project, ESLint was shouting at me when using `require`: https://typescript-eslint.io/rules/no-var-requires
Using `requireActual` resolved this:
```ts
jest.mock("next/router", () => jest.requireActual<MemoryRouter>("next-router-mock"));
```

docs(README): replace require with jest.requireActual

---

.changeset/thick-feet-return.md
src/MemoryRouter.tsx

This PR updates the library's own `UrlObject` to match the type defined in the native `url` module. `UrlObject` is defined in @types/node [v16](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0818c3f7de545c6b6431e9745dd9910618bba918/types/node/v16/url.d.ts#L15), [v18](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0818c3f7de545c6b6431e9745dd9910618bba918/types/node/v18/url.d.ts#L15) and [latest](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0818c3f7de545c6b6431e9745dd9910618bba918/types/node/url.d.ts#L15) as:
```ts
interface UrlObject {
auth?: string | null | undefined;
hash?: string | null | undefined;
host?: string | null | undefined;
hostname?: string | null | undefined;
href?: string | null | undefined;
pathname?: string | null | undefined;
protocol?: string …
```

fix: update UrlObject type to match native url module

---

.changeset/few-news-jam.md
package-lock.json
package.json
src/MemoryRouterProvider/MemoryRouterProvider.async.test.tsx
src/MemoryRouterProvider/MemoryRouterProvider.tsx

We are using the `next-router-mock/async` provider and had a bunch of issues with the Provider, as it appeared all manipulations of the router get ignored by our components.
Looking into the code, I discovered why: The `<MemoryRouterProvider />` ignores the `async` prop unless an `url` is given. However, when an `url` is given, a new router is created.
This should return the async singleton when requested - however, I could not test if it works for our application as I couldn't figure out how to include the package without it being published.

Use async singleton router for MemoryRouterProvider

---

README.md

First of all, thank you for creating and maintaining this wonderful package.
I looking this package, and found tiny issue, so i made this PR.
The link to "react-router" in "README" was broken because the URL of the linked repository had changed, so I fixed it.

docs: fix broken link to `react-router`

---

.changeset/sour-buttons-check.md
package-lock.json
package.json
src/MemoryRouter.test.tsx
src/MemoryRouter.tsx
src/urls.ts

This PR adds support for [search prop](https://nodejs.org/api/url.html#urlsearch) which while using the library we noticed it was yet not supported
Thanks a lot for this amazing package!

add support for search prop

---

README.md

The correct matcher is `toHaveTextContent` https://github.com/testing-library/jest-dom?tab=readme-ov-file#tohavetextcontent not `toHaveText`

Update README.md - fix code examples to use the correct of the testing-library matcher - toHaveTextContent

---

.changeset/selfish-doors-carry.md
package.json

Hello!
I always use your library, thank you!
After updating to “1.0.0”, I could not find the type definition file and got an [error](https://github.com/taro-28/tanstack-table-search-params/actions/runs/14924726878/job/41926905552?pr=527), so I added “types” to exports.

chore: update package.json exports to include TypeScript types
